# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='client',
            fields=[
                ('nickname', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=50)),
                ('id_number', models.CharField(max_length=9, null=True)),
                ('card_number', models.IntegerField(max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('number_of_rooms', models.IntegerField()),
                ('amount_of_people', models.IntegerField()),
                ('animal', models.BooleanField()),
                ('child', models.BooleanField()),
                ('parking_space', models.NullBooleanField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.city')),
            ],
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_rent', models.DateField()),
                ('end_rent', models.DateField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.flat')),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.client')),
            ],
        ),
    ]
