# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='card_number',
            field=models.IntegerField(null=True),
        ),
    ]
